name: Run Matrix Job

on:
  schedule:
    - cron: "0 12 * * 1"  # Every Monday at 12:00 (noon)
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    needs: enonces
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'linogaliana/python-datascientist-notebooks'
      - name: Define matrix
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find . -type f -name "*.ipynb" \
            ! -name "_*" \
            ! -regex '.*/getting-started/.*' \
            ! -regex '.*/modern-ds/.*' \
            ! -regex '.*/manipulation/04a_webscraping_TP.*' \
            ! -regex '.*/NLP/05_exo_supp.*' \
            | jq -R -s -c 'split("\n")[:-1]')"
